// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGatewayLogs(arg1:number):Promise<Array<string>>;

export function GetGatewayPID():Promise<number>;

export function GetGatewayStatus():Promise<string>;

export function GetSettings():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function HideWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function RestartGateway():Promise<string>;

export function SaveSettings(arg1:string):Promise<string>;

export function ShowWindow():Promise<void>;

export function StartGateway():Promise<string>;

export function StopGateway():Promise<string>;
