// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGatewayLogs(arg1) {
  return window['go']['main']['App']['GetGatewayLogs'](arg1);
}

export function GetGatewayPID() {
  return window['go']['main']['App']['GetGatewayPID']();
}

export function GetGatewayStatus() {
  return window['go']['main']['App']['GetGatewayStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function RestartGateway() {
  return window['go']['main']['App']['RestartGateway']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartGateway() {
  return window['go']['main']['App']['StartGateway']();
}

export function StopGateway() {
  return window['go']['main']['App']['StopGateway']();
}
